AWSTemplateFormatVersion: '2010-09-09'
Description: 'Quirehut Demo web app'

Resources:
  QuirehutWebTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      NetworkMode: awsvpc
      Cpu: .5 vCPU
      Memory: 1GB 
      RunTimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily : LINUX
      ContainerDefinitions:
        - Name: quirehut-demo-web
          Image: nginxdemos/hello
          Memory: 512
          Cpu: 256
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
              Protocol: tcp
          Essential: true
      ExecutionRoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole'

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !ImportValue quirehut-demo-Cluster
      TaskDefinition: !Ref QuirehutWebTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsVpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: 
           - !ImportValue quirehut-demo-subnet1-public