AWSTemplateFormatVersion: '2010-09-09'
Description: 'Quirehut Demo VPC with Public and Private Subnets'

Parameters:
  QuirehutDemoVpcCidr:
    Description: CIDR block for the VPC
    Type: String
    Default: 10.0.0.0/16

  QuirehutDemoPublicSubnet1Cidr:
    Description: CIDR block for Public Subnet 1
    Type: String
    Default: 10.0.1.0/24
  
  QuirehutDemoPublicSubnet2Cidr:
    Description: CIDR block for Public Subnet 2
    Type: String
    Default: 10.0.2.0/24

  QuirehutDemoPrivateSubnet1Cidr:
    Description: CIDR block for Private Subnet 1
    Type: String
    Default: 10.0.3.0/24

  QuirehutDemoPrivateSubnet2Cidr:
    Description: CIDR block for Private Subnet 2
    Type: String
    Default: 10.0.4.0/24

Resources:
  QuirehutDemoVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref QuirehutDemoVpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-vpc'

  QuirehutDemoPublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref QuirehutDemoPublicSubnet1Cidr
      VpcId: !Ref QuirehutDemoVpc
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-subnet1-public'
  
  QuirehutDemoPublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref QuirehutDemoPublicSubnet2Cidr
      VpcId: !Ref QuirehutDemoVpc
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-subnet2-public'

  QuirehutDemoPrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref QuirehutDemoPrivateSubnet1Cidr
      VpcId: !Ref QuirehutDemoVpc
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-subnet1-private'

  QuirehutDemoPrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref QuirehutDemoPrivateSubnet2Cidr
      VpcId: !Ref QuirehutDemoVpc
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-subnet2-private'

  QuirehutDemoIgw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-igw'

  QuirehutDemoIgwAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref QuirehutDemoIgw
      VpcId: !Ref QuirehutDemoVpc

  QuirehutDemoPublicRtb:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref QuirehutDemoVpc
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-rtb-public'

  QuirehutDemoDefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: QuirehutDemoIgwAttachment
    Properties:
      RouteTableId: !Ref QuirehutDemoPublicRtb
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref QuirehutDemoIgw

  QuirehutDemoPublicSubnet1RtbAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref QuirehutDemoPublicRtb
      SubnetId: !Ref QuirehutDemoPublicSubnet1
  
  QuirehutDemoPublicSubnet2RtbAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref QuirehutDemoPublicRtb
      SubnetId: !Ref QuirehutDemoPublicSubnet2

  QuirehutDemoPrivateRtb:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref QuirehutDemoVpc
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-rtb-private'

  QuirehutDemoPrivateSubnet1RtbAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref QuirehutDemoPrivateRtb
      SubnetId: !Ref QuirehutDemoPrivateSubnet1

  QuirehutDemoPrivateSubnet2RtbAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref QuirehutDemoPrivateRtb
      SubnetId: !Ref QuirehutDemoPrivateSubnet2

Outputs:
  QuirehutDemoVpc:
    Description: 'A reference to the created vpc'
    Value: !Ref QuirehutDemoVpc
    Export:
      Name: QuirehutDemoVpc

  QuirehutDemoPublicSubnets:
    Description: 'A list of the public subnets in vpc'
    Value: !Join [",", [ !Ref QuirehutDemoPublicSubnet1, !Ref QuirehutDemoPublicSubnet2 ]]
    Export:
      Name: QuirehutDemoPublicSubnets

  QuirehutDemoPrivateSubnets:
    Description: 'A list of the private subnets in vpc'
    Value: !Join [ ",", [ !Ref QuirehutDemoPrivateSubnet1, !Ref QuirehutDemoPrivateSubnet2 ]]
    Export:
      Name: QuirehutDemoPrivateSubnets

  QuirehutDemoPublicSubnet1:
    Description: 'A reference to the public subnet 1'
    Value: !Ref QuirehutDemoPublicSubnet1
    Export:
      Name: QuirehutDemoPublicSubnet1
  
  QuirehutDemoPublicSubnet2:
    Description: 'A reference to the public subnet 2'
    Value: !Ref QuirehutDemoPublicSubnet2
    Export:
      Name: QuirehutDemoPublicSubnet2

  QuirehutDemoPrivateSubnet1:
    Description: 'A reference to the private subnet 1 in the 1st Availability Zone'
    Value: !Ref QuirehutDemoPrivateSubnet1
    Export:
      Name: QuirehutDemoPrivateSubnet1

  QuirehutDemoPrivateSubnet2:
    Description: 'A reference to the private subnet 2 in the 2nd Availability Zone'
    Value: !Ref QuirehutDemoPrivateSubnet2
    Export:
      Name: QuirehutDemoPrivateSubnet2
